version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - 'GitHub Actions'
      - 'dependencies'

  - package-ecosystem: 'terraform'
    directory: '/Infra'
    schedule:
      interval: 'weekly'
    labels:
      - 'IaC/Terraform'
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: '/App/FrontendPortal'
    schedule:
      interval: 'weekly'
    labels:
      - 'Frontend'
      - 'dependencies'
